set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR "X86")

set(CMAKE_TRY_COMPILE_TARGET_TYPE   STATIC_LIBRARY)
set(CMAKE_ASM_COMPILER  "gcc")
set(CMAKE_C_COMPILER    "gcc")
set(CMAKE_CXX_COMPILER  "g++")

# Set compiler to maximum optimization and remove all debug code from the compiled file 
set(CMAKE_C_FLAGS_DEBUG     "-g -O0" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELEASE   "-Os" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG}" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}" CACHE INTERNAL "")


# Options for specific architecture)
set(EXTRA_OPTIONS       "-Wall -Wextra")
set(CMAKE_C_FLAGS       "${CMAKE_C_FLAGS} ${EXTRA_OPTIONS}" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS     "${CMAKE_CXX_FLAGS} ${CMAKE_C_FLAGS}" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
