# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/github/stm_drone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/github/stm_drone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/github/stm_drone/CMakeFiles C:/github/stm_drone/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/github/stm_drone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stm_drone

# Build rule for target.
stm_drone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stm_drone
.PHONY : stm_drone

# fast build rule for target.
stm_drone/fast:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/build
.PHONY : stm_drone/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

drivers/hal/src/stm32f7xx_hal.obj: drivers/hal/src/stm32f7xx_hal.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal.c.obj

drivers/hal/src/stm32f7xx_hal.i: drivers/hal/src/stm32f7xx_hal.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal.c.i

drivers/hal/src/stm32f7xx_hal.s: drivers/hal/src/stm32f7xx_hal.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal.c.s

drivers/hal/src/stm32f7xx_hal_cortex.obj: drivers/hal/src/stm32f7xx_hal_cortex.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal_cortex.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal_cortex.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_cortex.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal_cortex.c.obj

drivers/hal/src/stm32f7xx_hal_cortex.i: drivers/hal/src/stm32f7xx_hal_cortex.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal_cortex.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal_cortex.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_cortex.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal_cortex.c.i

drivers/hal/src/stm32f7xx_hal_cortex.s: drivers/hal/src/stm32f7xx_hal_cortex.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal_cortex.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal_cortex.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_cortex.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal_cortex.c.s

drivers/hal/src/stm32f7xx_hal_dma.obj: drivers/hal/src/stm32f7xx_hal_dma.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal_dma.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal_dma.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_dma.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal_dma.c.obj

drivers/hal/src/stm32f7xx_hal_dma.i: drivers/hal/src/stm32f7xx_hal_dma.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal_dma.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal_dma.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_dma.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal_dma.c.i

drivers/hal/src/stm32f7xx_hal_dma.s: drivers/hal/src/stm32f7xx_hal_dma.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal_dma.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal_dma.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_dma.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal_dma.c.s

drivers/hal/src/stm32f7xx_hal_gpio.obj: drivers/hal/src/stm32f7xx_hal_gpio.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal_gpio.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal_gpio.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_gpio.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal_gpio.c.obj

drivers/hal/src/stm32f7xx_hal_gpio.i: drivers/hal/src/stm32f7xx_hal_gpio.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal_gpio.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal_gpio.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_gpio.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal_gpio.c.i

drivers/hal/src/stm32f7xx_hal_gpio.s: drivers/hal/src/stm32f7xx_hal_gpio.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal_gpio.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal_gpio.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_gpio.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal_gpio.c.s

drivers/hal/src/stm32f7xx_hal_i2c.obj: drivers/hal/src/stm32f7xx_hal_i2c.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal_i2c.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal_i2c.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_i2c.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal_i2c.c.obj

drivers/hal/src/stm32f7xx_hal_i2c.i: drivers/hal/src/stm32f7xx_hal_i2c.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal_i2c.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal_i2c.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_i2c.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal_i2c.c.i

drivers/hal/src/stm32f7xx_hal_i2c.s: drivers/hal/src/stm32f7xx_hal_i2c.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal_i2c.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal_i2c.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_i2c.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal_i2c.c.s

drivers/hal/src/stm32f7xx_hal_i2c_ex.obj: drivers/hal/src/stm32f7xx_hal_i2c_ex.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal_i2c_ex.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal_i2c_ex.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_i2c_ex.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal_i2c_ex.c.obj

drivers/hal/src/stm32f7xx_hal_i2c_ex.i: drivers/hal/src/stm32f7xx_hal_i2c_ex.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal_i2c_ex.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal_i2c_ex.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_i2c_ex.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal_i2c_ex.c.i

drivers/hal/src/stm32f7xx_hal_i2c_ex.s: drivers/hal/src/stm32f7xx_hal_i2c_ex.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal_i2c_ex.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal_i2c_ex.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_i2c_ex.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal_i2c_ex.c.s

drivers/hal/src/stm32f7xx_hal_rcc.obj: drivers/hal/src/stm32f7xx_hal_rcc.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal_rcc.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal_rcc.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_rcc.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal_rcc.c.obj

drivers/hal/src/stm32f7xx_hal_rcc.i: drivers/hal/src/stm32f7xx_hal_rcc.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal_rcc.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal_rcc.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_rcc.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal_rcc.c.i

drivers/hal/src/stm32f7xx_hal_rcc.s: drivers/hal/src/stm32f7xx_hal_rcc.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal_rcc.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal_rcc.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_rcc.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal_rcc.c.s

drivers/hal/src/stm32f7xx_hal_uart.obj: drivers/hal/src/stm32f7xx_hal_uart.c.obj

.PHONY : drivers/hal/src/stm32f7xx_hal_uart.obj

# target to build an object file
drivers/hal/src/stm32f7xx_hal_uart.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_uart.c.obj
.PHONY : drivers/hal/src/stm32f7xx_hal_uart.c.obj

drivers/hal/src/stm32f7xx_hal_uart.i: drivers/hal/src/stm32f7xx_hal_uart.c.i

.PHONY : drivers/hal/src/stm32f7xx_hal_uart.i

# target to preprocess a source file
drivers/hal/src/stm32f7xx_hal_uart.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_uart.c.i
.PHONY : drivers/hal/src/stm32f7xx_hal_uart.c.i

drivers/hal/src/stm32f7xx_hal_uart.s: drivers/hal/src/stm32f7xx_hal_uart.c.s

.PHONY : drivers/hal/src/stm32f7xx_hal_uart.s

# target to generate assembly for a file
drivers/hal/src/stm32f7xx_hal_uart.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/drivers/hal/src/stm32f7xx_hal_uart.c.s
.PHONY : drivers/hal/src/stm32f7xx_hal_uart.c.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/main.cpp.s
.PHONY : main.cpp.s

src/board_config.obj: src/board_config.c.obj

.PHONY : src/board_config.obj

# target to build an object file
src/board_config.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/board_config.c.obj
.PHONY : src/board_config.c.obj

src/board_config.i: src/board_config.c.i

.PHONY : src/board_config.i

# target to preprocess a source file
src/board_config.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/board_config.c.i
.PHONY : src/board_config.c.i

src/board_config.s: src/board_config.c.s

.PHONY : src/board_config.s

# target to generate assembly for a file
src/board_config.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/board_config.c.s
.PHONY : src/board_config.c.s

src/error_handling.obj: src/error_handling.c.obj

.PHONY : src/error_handling.obj

# target to build an object file
src/error_handling.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/error_handling.c.obj
.PHONY : src/error_handling.c.obj

src/error_handling.i: src/error_handling.c.i

.PHONY : src/error_handling.i

# target to preprocess a source file
src/error_handling.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/error_handling.c.i
.PHONY : src/error_handling.c.i

src/error_handling.s: src/error_handling.c.s

.PHONY : src/error_handling.s

# target to generate assembly for a file
src/error_handling.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/error_handling.c.s
.PHONY : src/error_handling.c.s

src/i2c.obj: src/i2c.c.obj

.PHONY : src/i2c.obj

# target to build an object file
src/i2c.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/i2c.c.obj
.PHONY : src/i2c.c.obj

src/i2c.i: src/i2c.c.i

.PHONY : src/i2c.i

# target to preprocess a source file
src/i2c.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/i2c.c.i
.PHONY : src/i2c.c.i

src/i2c.s: src/i2c.c.s

.PHONY : src/i2c.s

# target to generate assembly for a file
src/i2c.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/i2c.c.s
.PHONY : src/i2c.c.s

src/retarget.obj: src/retarget.c.obj

.PHONY : src/retarget.obj

# target to build an object file
src/retarget.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/retarget.c.obj
.PHONY : src/retarget.c.obj

src/retarget.i: src/retarget.c.i

.PHONY : src/retarget.i

# target to preprocess a source file
src/retarget.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/retarget.c.i
.PHONY : src/retarget.c.i

src/retarget.s: src/retarget.c.s

.PHONY : src/retarget.s

# target to generate assembly for a file
src/retarget.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/retarget.c.s
.PHONY : src/retarget.c.s

src/stm32f7xx_hal_msp.obj: src/stm32f7xx_hal_msp.c.obj

.PHONY : src/stm32f7xx_hal_msp.obj

# target to build an object file
src/stm32f7xx_hal_msp.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/stm32f7xx_hal_msp.c.obj
.PHONY : src/stm32f7xx_hal_msp.c.obj

src/stm32f7xx_hal_msp.i: src/stm32f7xx_hal_msp.c.i

.PHONY : src/stm32f7xx_hal_msp.i

# target to preprocess a source file
src/stm32f7xx_hal_msp.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/stm32f7xx_hal_msp.c.i
.PHONY : src/stm32f7xx_hal_msp.c.i

src/stm32f7xx_hal_msp.s: src/stm32f7xx_hal_msp.c.s

.PHONY : src/stm32f7xx_hal_msp.s

# target to generate assembly for a file
src/stm32f7xx_hal_msp.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/stm32f7xx_hal_msp.c.s
.PHONY : src/stm32f7xx_hal_msp.c.s

src/stm32f7xx_it.obj: src/stm32f7xx_it.c.obj

.PHONY : src/stm32f7xx_it.obj

# target to build an object file
src/stm32f7xx_it.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/stm32f7xx_it.c.obj
.PHONY : src/stm32f7xx_it.c.obj

src/stm32f7xx_it.i: src/stm32f7xx_it.c.i

.PHONY : src/stm32f7xx_it.i

# target to preprocess a source file
src/stm32f7xx_it.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/stm32f7xx_it.c.i
.PHONY : src/stm32f7xx_it.c.i

src/stm32f7xx_it.s: src/stm32f7xx_it.c.s

.PHONY : src/stm32f7xx_it.s

# target to generate assembly for a file
src/stm32f7xx_it.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/stm32f7xx_it.c.s
.PHONY : src/stm32f7xx_it.c.s

src/system_stm32f7xx.obj: src/system_stm32f7xx.c.obj

.PHONY : src/system_stm32f7xx.obj

# target to build an object file
src/system_stm32f7xx.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/system_stm32f7xx.c.obj
.PHONY : src/system_stm32f7xx.c.obj

src/system_stm32f7xx.i: src/system_stm32f7xx.c.i

.PHONY : src/system_stm32f7xx.i

# target to preprocess a source file
src/system_stm32f7xx.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/system_stm32f7xx.c.i
.PHONY : src/system_stm32f7xx.c.i

src/system_stm32f7xx.s: src/system_stm32f7xx.c.s

.PHONY : src/system_stm32f7xx.s

# target to generate assembly for a file
src/system_stm32f7xx.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/system_stm32f7xx.c.s
.PHONY : src/system_stm32f7xx.c.s

src/usart.obj: src/usart.c.obj

.PHONY : src/usart.obj

# target to build an object file
src/usart.c.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/usart.c.obj
.PHONY : src/usart.c.obj

src/usart.i: src/usart.c.i

.PHONY : src/usart.i

# target to preprocess a source file
src/usart.c.i:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/usart.c.i
.PHONY : src/usart.c.i

src/usart.s: src/usart.c.s

.PHONY : src/usart.s

# target to generate assembly for a file
src/usart.c.s:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/src/usart.c.s
.PHONY : src/usart.c.s

startup/startup_ARMCM7.obj: startup/startup_ARMCM7.S.obj

.PHONY : startup/startup_ARMCM7.obj

# target to build an object file
startup/startup_ARMCM7.S.obj:
	$(MAKE) -f CMakeFiles/stm_drone.dir/build.make CMakeFiles/stm_drone.dir/startup/startup_ARMCM7.S.obj
.PHONY : startup/startup_ARMCM7.S.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... stm_drone"
	@echo "... flash"
	@echo "... rebuild_cache"
	@echo "... drivers/hal/src/stm32f7xx_hal.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal.i"
	@echo "... drivers/hal/src/stm32f7xx_hal.s"
	@echo "... drivers/hal/src/stm32f7xx_hal_cortex.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal_cortex.i"
	@echo "... drivers/hal/src/stm32f7xx_hal_cortex.s"
	@echo "... drivers/hal/src/stm32f7xx_hal_dma.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal_dma.i"
	@echo "... drivers/hal/src/stm32f7xx_hal_dma.s"
	@echo "... drivers/hal/src/stm32f7xx_hal_gpio.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal_gpio.i"
	@echo "... drivers/hal/src/stm32f7xx_hal_gpio.s"
	@echo "... drivers/hal/src/stm32f7xx_hal_i2c.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal_i2c.i"
	@echo "... drivers/hal/src/stm32f7xx_hal_i2c.s"
	@echo "... drivers/hal/src/stm32f7xx_hal_i2c_ex.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal_i2c_ex.i"
	@echo "... drivers/hal/src/stm32f7xx_hal_i2c_ex.s"
	@echo "... drivers/hal/src/stm32f7xx_hal_rcc.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal_rcc.i"
	@echo "... drivers/hal/src/stm32f7xx_hal_rcc.s"
	@echo "... drivers/hal/src/stm32f7xx_hal_uart.obj"
	@echo "... drivers/hal/src/stm32f7xx_hal_uart.i"
	@echo "... drivers/hal/src/stm32f7xx_hal_uart.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/board_config.obj"
	@echo "... src/board_config.i"
	@echo "... src/board_config.s"
	@echo "... src/error_handling.obj"
	@echo "... src/error_handling.i"
	@echo "... src/error_handling.s"
	@echo "... src/i2c.obj"
	@echo "... src/i2c.i"
	@echo "... src/i2c.s"
	@echo "... src/retarget.obj"
	@echo "... src/retarget.i"
	@echo "... src/retarget.s"
	@echo "... src/stm32f7xx_hal_msp.obj"
	@echo "... src/stm32f7xx_hal_msp.i"
	@echo "... src/stm32f7xx_hal_msp.s"
	@echo "... src/stm32f7xx_it.obj"
	@echo "... src/stm32f7xx_it.i"
	@echo "... src/stm32f7xx_it.s"
	@echo "... src/system_stm32f7xx.obj"
	@echo "... src/system_stm32f7xx.i"
	@echo "... src/system_stm32f7xx.s"
	@echo "... src/usart.obj"
	@echo "... src/usart.i"
	@echo "... src/usart.s"
	@echo "... startup/startup_ARMCM7.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

